{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common",
    "version": "2.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13444738"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.9.0-multiplatform-sources.jar",
          "url": "navigation-common-2.9.0-multiplatform-sources.jar",
          "size": 118540,
          "sha512": "323d8b4fd508302864be457bceec6ca85bd581f1b5ecce32e38697c618a4237ec60e3ebfa79b4610ee0d47fd20d050c78241e9b9997844e56532b0e0afd7bab0",
          "sha256": "c756ca1544ea90c1fbdaa8199a2614e091f82a68afdcfb2a59ade08b65cf109e",
          "sha1": "6a63fd701c633529aa206630da5126f2310c946d",
          "md5": "ced8c530eb54c28b1ca5938cc754b941"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "navigation-common-2.9.0-versionMetadata.json",
          "size": 31705,
          "sha512": "b1cb14e2fbeecf6be5b7eea969c740fb239b7df240b24eb609c6fe1676050b7141abe72a86be9011e78252e7dbd078473aa50b094d739f8eeceaed0c4dad3b3c",
          "sha256": "c3251ea0f42a28bdf293618444a3c803b9e9f11724d2bec86b2d30085270c1ab",
          "sha1": "2bd3806e919e3e09e47ed1f616babf256b3a81b7",
          "md5": "bd74429b3dffdbeda3de7a9dc3ccdd38"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-common-metadata-2.9.0.jar",
          "url": "navigation-common-2.9.0.jar",
          "size": 51341,
          "sha512": "d61c75865cc277eec8fc4ae032f6adf7bb82b56dc3bb5409434891f975562f7699f57e983a015cab93810804a9b10f42228e8778622835c195640754a6ac25f9",
          "sha256": "2c94f29cf065ef7c6f73da15867eff35fb4aca1c9e46801f3c0dca6efa79e40e",
          "sha1": "38e11748730d494b546fdeb74091a884f4d0e54c",
          "md5": "b0d6a267387358188e42e365c4c13711"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-common-kotlin-2.9.0-sources.jar",
          "url": "navigation-common-2.9.0-sources.jar",
          "size": 99723,
          "sha512": "2957307550e606fc6e1665cb25ad994ef597da876117853b7151ee000e0730bed2e25dfe2c4a21c03c51888c738ceae9324586b56b309dc1b0fc9bc85fae4cfe",
          "sha256": "0268627fdc639c41e9c6361b219406222d0ed02c42fd5a463adc04acef81b004",
          "sha1": "ff2d88c020f0e69508d7ff67a663bd2529dc4332",
          "md5": "a027ca396f8b3e9c8d01c752066e7def"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../navigation-common-android/2.9.0/navigation-common-android-2.9.0.module",
        "group": "androidx.navigation",
        "module": "navigation-common-android",
        "version": "2.9.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../navigation-common-android/2.9.0/navigation-common-android-2.9.0.module",
        "group": "androidx.navigation",
        "module": "navigation-common-android",
        "version": "2.9.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../navigation-common-android/2.9.0/navigation-common-android-2.9.0.module",
        "group": "androidx.navigation",
        "module": "navigation-common-android",
        "version": "2.9.0"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigation-common-jvmstubs/2.9.0/navigation-common-jvmstubs-2.9.0.module",
        "group": "androidx.navigation",
        "module": "navigation-common-jvmstubs",
        "version": "2.9.0"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigation-common-jvmstubs/2.9.0/navigation-common-jvmstubs-2.9.0.module",
        "group": "androidx.navigation",
        "module": "navigation-common-jvmstubs",
        "version": "2.9.0"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigation-common-jvmstubs/2.9.0/navigation-common-jvmstubs-2.9.0.module",
        "group": "androidx.navigation",
        "module": "navigation-common-jvmstubs",
        "version": "2.9.0"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-common-linuxx64stubs/2.9.0/navigation-common-linuxx64stubs-2.9.0.module",
        "group": "androidx.navigation",
        "module": "navigation-common-linuxx64stubs",
        "version": "2.9.0"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-common-linuxx64stubs/2.9.0/navigation-common-linuxx64stubs-2.9.0.module",
        "group": "androidx.navigation",
        "module": "navigation-common-linuxx64stubs",
        "version": "2.9.0"
      }
    }
  ]
}