{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.savedstate",
    "module": "savedstate-ktx",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13433626"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.3.0-sources.jar",
          "url": "savedstate-ktx-1.3.0-sources.jar",
          "size": 4426,
          "sha512": "470b68b1ba0bbefe5afcf0a072635a72e5080f040860d900c972c9797c1ab4c2402ad6a622477ea916ecc6ece19b0290e15a391f7f1a0ea00c612b1da3ea6d82",
          "sha256": "b1e8d78600a68fb3c0029793146ac07ea0335819f813554e85c568caa35cb5e4",
          "sha1": "d281a4d66d1b5ed25c21373dedb46a67918618d9",
          "md5": "c7dd8c25948273de8256385c8a05e3d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.3.0.aar",
          "url": "savedstate-ktx-1.3.0.aar",
          "size": 5763,
          "sha512": "87e4292c9cb93aa36681fd17b33da7dd2801b93584caeff1906df8c88dfb7e68df9658f26e06e2b6fb12134d71da77ef95ccfd6e5403f3ec28083041086ece0a",
          "sha256": "45c5f6412840f50de7bf7d9b1c4a8c81ea236832487a1138cb320b8c997416f2",
          "sha1": "2ecb96859cdd5b642770ece814d8fca666781410",
          "md5": "c02396230081a28ff8d21b78fd8cbfea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.3.0.aar",
          "url": "savedstate-ktx-1.3.0.aar",
          "size": 5763,
          "sha512": "87e4292c9cb93aa36681fd17b33da7dd2801b93584caeff1906df8c88dfb7e68df9658f26e06e2b6fb12134d71da77ef95ccfd6e5403f3ec28083041086ece0a",
          "sha256": "45c5f6412840f50de7bf7d9b1c4a8c81ea236832487a1138cb320b8c997416f2",
          "sha1": "2ecb96859cdd5b642770ece814d8fca666781410",
          "md5": "c02396230081a28ff8d21b78fd8cbfea"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.3.0-versionMetadata.json",
          "url": "savedstate-ktx-1.3.0-versionMetadata.json",
          "size": 191,
          "sha512": "225072cf1e54fc7479700f5339019ceafe1f9e4d514a8893a626190d42dfb31b35804c73597292ee864e5f3034bc73b4c5806109ed130eb268c531948a4be4b7",
          "sha256": "ff1847220d3c526a133e4f76baed2060de09a72ac96f5b8e1fef2ab1d21ba85e",
          "sha1": "a1a2692ed79fa0caa20fafeb33e56bd48993f6de",
          "md5": "57c4eed7a9c15485d30d344fdc944a0a"
        }
      ]
    }
  ]
}