{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.credentials",
    "module": "credentials-play-services-auth",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "credentials-play-services-auth is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-play-services-auth-1.3.0-sources.jar",
          "url": "credentials-play-services-auth-1.3.0-sources.jar",
          "size": 35472,
          "sha512": "7194a8f7831497dc8e9f9d02cf62438b91f777b09dfafd382d6415829be5b677bdf7f16971defa70a9c080fe00e19c0abeeb9fc592412352664c652e74980b39",
          "sha256": "65202669ac2eada96cbf57e403c5be0b44700233d45e2fefe880ca71562decd6",
          "sha1": "6b4591311ef045d82d9e000172743ee850671479",
          "md5": "b98846cd5feb268eee44c7c159b584e4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "credentials-play-services-auth is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-play-services-auth-1.3.0.aar",
          "url": "credentials-play-services-auth-1.3.0.aar",
          "size": 134130,
          "sha512": "bc24c019c88a0048f41e3564b4664d763c3ce9db799d6b1529ffb82b87728730453435c7b3ac482096d30a98dac3781a88f3ba69aa9008ee2375127c927cebbf",
          "sha256": "7ded50690900ed0bfe1f71ffd403cb0a53eabd74510f8fcc4474f8749742e3e7",
          "sha1": "7ffddb89b9c7f9fc429753070d3cc96b21635b28",
          "md5": "9f13d40f6789775e4f2d52b37adb0f98"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "21.1.1"
          },
          "excludes": [
            {
              "group": "androidx.loader",
              "module": "*"
            },
            {
              "group": "androidx.core",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-fido",
          "version": {
            "requires": "21.0.0"
          },
          "excludes": [
            {
              "group": "androidx.loader",
              "module": "*"
            },
            {
              "group": "androidx.core",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.android.libraries.identity.googleid",
          "module": "googleid",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "androidx.credentials",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "credentials-play-services-auth is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-play-services-auth-1.3.0.aar",
          "url": "credentials-play-services-auth-1.3.0.aar",
          "size": 134130,
          "sha512": "bc24c019c88a0048f41e3564b4664d763c3ce9db799d6b1529ffb82b87728730453435c7b3ac482096d30a98dac3781a88f3ba69aa9008ee2375127c927cebbf",
          "sha256": "7ded50690900ed0bfe1f71ffd403cb0a53eabd74510f8fcc4474f8749742e3e7",
          "sha1": "7ffddb89b9c7f9fc429753070d3cc96b21635b28",
          "md5": "9f13d40f6789775e4f2d52b37adb0f98"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "credentials-play-services-auth is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-play-services-auth-1.3.0-versionMetadata.json",
          "url": "credentials-play-services-auth-1.3.0-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}