{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-runtime",
    "version": "2.10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.10.1-sources.jar",
          "url": "work-runtime-2.10.1-sources.jar",
          "size": 304207,
          "sha512": "f3ac5c9ff70be541776561be21ada4c63e4cb9544e3b5f19717bfeb87a6eb377375c829b89ccfdd4232841619ce2ce7540ca07298354463005016104e4e8f2fc",
          "sha256": "d2d5128a13ad741c5977538db8a5aafb827544036b28fadf651e951f8ed83456",
          "sha1": "1cf0af27d856a171b7b3317c70f143a1723a0619",
          "md5": "086ce47f43873a338a18fb2eb9373e99"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.10.1.aar",
          "url": "work-runtime-2.10.1.aar",
          "size": 2022206,
          "sha512": "6447f8f94161e2b6e5fe7e6ee61f38723d2d2ce99b62d858a0b88b67203b131f8f7a3a32879e0a507ada94450c6681e3d4d03e49b332c417b36073d1361d1ee0",
          "sha256": "c5b97873987e50fbc19ddcab971a6a0f108087423a8cebd15c274db0d07e2245",
          "sha1": "d512122f1cf7a3e7623884678323d0f9616d701d",
          "md5": "3c13ecab34c13518348081b8f266f14c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.10.1.aar",
          "url": "work-runtime-2.10.1.aar",
          "size": 2022206,
          "sha512": "6447f8f94161e2b6e5fe7e6ee61f38723d2d2ce99b62d858a0b88b67203b131f8f7a3a32879e0a507ada94450c6681e3d4d03e49b332c417b36073d1361d1ee0",
          "sha256": "c5b97873987e50fbc19ddcab971a6a0f108087423a8cebd15c274db0d07e2245",
          "sha1": "d512122f1cf7a3e7623884678323d0f9616d701d",
          "md5": "3c13ecab34c13518348081b8f266f14c"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.10.1-versionMetadata.json",
          "url": "work-runtime-2.10.1-versionMetadata.json",
          "size": 37017,
          "sha512": "956a71103277666d2bcd9a290ec203b720826c9b39516037bd8123e4c0c69dbbe27e5c4e3c20dbc0d0dbb1ee2db200689022b9fffb4d24dae27d99619fe4cac5",
          "sha256": "a38812134642aa936fdf7918581f8bf598851fea8ec55026163bd39a65e674bd",
          "sha1": "7d3d579a4a0e4d55108f1d59545ee10b4b344c0e",
          "md5": "1f348319279110216775d786ca2c53cf"
        }
      ]
    }
  ]
}