{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.recyclerview",
    "module": "recyclerview",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recyclerview-1.4.0-sources.jar",
          "url": "recyclerview-1.4.0-sources.jar",
          "size": 340940,
          "sha512": "4e93b5837136959bb75d5088fa334482dd864dbca830cd4195d25fd533a9b17a4b93211087edbfe63a9effab60a410ad3629a2497c9bfa5a980d11a201175379",
          "sha256": "cad83357a7003b5903197be0494f6e8f6825fa1338ee6b09b06a8dea32a97cb8",
          "sha1": "e7e910392b8ee3c7bb8b09d365879ef0cefe198b",
          "md5": "37a80a15c2a3ddf3e72716ec50a173f5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.4.0.aar",
          "url": "recyclerview-1.4.0.aar",
          "size": 452493,
          "sha512": "cb19cdf6618be23a41d629146d19b670ab6dba745ec476cc248ca365c8df1306ca26efb98aad83068c29ba9cdebf6529c0a008fd80806449e91db495892d7dd1",
          "sha256": "0f32ccaffcda74c3f87f0b4cfe6ae78e8aa4eb3ad7dda4f2edf06eedc947a5cf",
          "sha1": "0764103dfd078c2bba394ce0ae1c3a52ace27dc3",
          "md5": "ecc7fd857af3af6d2c33826fd0c1b7d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview-poolingcontainer",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.4.0.aar",
          "url": "recyclerview-1.4.0.aar",
          "size": 452493,
          "sha512": "cb19cdf6618be23a41d629146d19b670ab6dba745ec476cc248ca365c8df1306ca26efb98aad83068c29ba9cdebf6529c0a008fd80806449e91db495892d7dd1",
          "sha256": "0f32ccaffcda74c3f87f0b4cfe6ae78e8aa4eb3ad7dda4f2edf06eedc947a5cf",
          "sha1": "0764103dfd078c2bba394ce0ae1c3a52ace27dc3",
          "md5": "ecc7fd857af3af6d2c33826fd0c1b7d4"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "recyclerview-1.4.0-versionMetadata.json",
          "url": "recyclerview-1.4.0-versionMetadata.json",
          "size": 74533,
          "sha512": "e1ee5751cfb1abcf32e8e181f02161a37929f29c7769b7f79057ea880071d54373250ac0e2aacd0c44dcce9362721002de6824d7cd8924ce7118cf678bf05e04",
          "sha256": "20d68898bc0935c5c43b45f5f2fc2cc283f54f3f9679b38f2ed7ffec9fbad757",
          "sha1": "ef294071ace71628222b950ef3300513015c88a5",
          "md5": "cd263007dd6e8ef15c7db7bb8da57daf"
        }
      ]
    }
  ]
}