{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-runtime-ktx",
    "version": "2.10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-runtime-ktx-2.10.1-sources.jar",
          "url": "work-runtime-ktx-2.10.1-sources.jar",
          "size": 4398,
          "sha512": "eaaa9f9f26a7c979c48aa131e1a39b091f73c3d63b4ec209f4cf8c848bd4c22354e8c2cdba41e68e72c69793624ba72f60f8e7a705ef2213ec7683217b5b8f28",
          "sha256": "4a5f293a931444d1cb766fb365bfcc2c286cd8ae43fdedad0cdfa2a69362ed15",
          "sha1": "66ac1feafafc2d29b82f59287681b0f806a662b7",
          "md5": "0bcab478160980290b15a4759d9b600c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-runtime-ktx-2.10.1.aar",
          "url": "work-runtime-ktx-2.10.1.aar",
          "size": 5928,
          "sha512": "ea61f3b6de3b90bee5f6ce852d18b060ff6441a6cdf44cd4e37f9d3569988fdc0fc002849bb4e0c68ad8216469c0a0142aa857e6d94a28b3da2a34c55336b69d",
          "sha256": "7c9691b00b04aa92ec5fe03ef1738d168a86d2e2523af39e9e9e4761b997847d",
          "sha1": "d6e8a9aa3fb9e4099e7c3e4f1af619f689ac444b",
          "md5": "679ac5b9b0a6c179fc37d75831669404"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-runtime-ktx-2.10.1.aar",
          "url": "work-runtime-ktx-2.10.1.aar",
          "size": 5928,
          "sha512": "ea61f3b6de3b90bee5f6ce852d18b060ff6441a6cdf44cd4e37f9d3569988fdc0fc002849bb4e0c68ad8216469c0a0142aa857e6d94a28b3da2a34c55336b69d",
          "sha256": "7c9691b00b04aa92ec5fe03ef1738d168a86d2e2523af39e9e9e4761b997847d",
          "sha1": "d6e8a9aa3fb9e4099e7c3e4f1af619f689ac444b",
          "md5": "679ac5b9b0a6c179fc37d75831669404"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.1"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-runtime-ktx-2.10.1-versionMetadata.json",
          "url": "work-runtime-ktx-2.10.1-versionMetadata.json",
          "size": 3007,
          "sha512": "2935c1bd7b2309f87bd8036a40b99dd68820d73edcfdcc0acbda49f5d2e0f459f63d0a051e4aad216c46ffb7a80df7fe1d1684475e2b587abb2b3b468203f5f3",
          "sha256": "6125d9ef70538992093ff3f92bbcddb533fb23bff67c831c10dc8396261bfa01",
          "sha1": "21a8d647b22f503ec8017801435e34752ae38c81",
          "md5": "bb6d1d3239f9b605383142a5eee656e5"
        }
      ]
    }
  ]
}