{
  "formatVersion": "1.1",
  "component": {
    "url": "../../savedstate/1.3.0/savedstate-1.3.0.module",
    "group": "androidx.savedstate",
    "module": "savedstate",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13433626"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-release.aar",
          "url": "savedstate-android-1.3.0.aar",
          "size": 140531,
          "sha512": "239156e546f678f69a7367dc75470d048b25086e20a0d2aecb183f8667754f7f80631840dd6c46aa350a5e234430db565c460bf1568895f4118919fe66108331",
          "sha256": "210b6909bbd515dbf415905cbb220fca93a87fa546838f754077ebc8e0488590",
          "sha1": "18b764de9745867c9eb92404b2aac85d59fab28f",
          "md5": "3c46a7bae6efbda356d3df2727bf36ce"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-viewtree",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-release.aar",
          "url": "savedstate-android-1.3.0.aar",
          "size": 140531,
          "sha512": "239156e546f678f69a7367dc75470d048b25086e20a0d2aecb183f8667754f7f80631840dd6c46aa350a5e234430db565c460bf1568895f4118919fe66108331",
          "sha256": "210b6909bbd515dbf415905cbb220fca93a87fa546838f754077ebc8e0488590",
          "sha1": "18b764de9745867c9eb92404b2aac85d59fab28f",
          "md5": "3c46a7bae6efbda356d3df2727bf36ce"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "savedstate-1.3.0-samples-sources.jar",
          "url": "savedstate-android-1.3.0-samples-sources.jar",
          "size": 7259,
          "sha512": "ad179ef3e460809ceacda099a5359c56618e1ffed48f9cbb7a359a4f8d196c5b1565b01ca6965881847715ed7ae47d048ed7737f0d68ae76e2c07c37fcb0da0e",
          "sha256": "53346ce0ace2e73c49030da45c03357ed857ec819d82f6da43ba8a22539b39e6",
          "sha1": "a5a55eb6311a88e40e1661eeb1e2ee1eec95926f",
          "md5": "c2a1444de3e44722df513b82ab8f3a9a"
        },
        {
          "name": "savedstate-android-1.3.0-sources.jar",
          "url": "savedstate-android-1.3.0-sources.jar",
          "size": 53661,
          "sha512": "d4e906026ec7bd9d20a8026a907a0a0bd6adc0a53412b9a7e1bcc0261bce7d4b50501a3d64aa4bb685350c2ffc5b17ea5677f0a909a6e9d9bc4238bd8bcdd75b",
          "sha256": "11078e1dc3071f58864e6d5709ce6922bf87c2d9685a9e0591dcce85f3629221",
          "sha1": "e0fc72ae9d6fc7a2ebb59704075e0593657945a8",
          "md5": "44d56b1c4ee2c7473baa2f4772b56f48"
        }
      ]
    }
  ]
}