{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "viewbinding",
    "version": "9.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-9.0.1.aar",
          "url": "viewbinding-9.0.1.aar",
          "size": 1861,
          "sha512": "cca33022607d03648a8e4df5253791f3071e6db503efe57747e88a3f8ab089c63f5c9c3d632e86a426d7d9164960c26d96e7a7325aa74d436fc84cb973c71867",
          "sha256": "9c6875bea4e43027209a3a7ef3d99524aca7c16797a2e6794afc62fbfbab7e28",
          "sha1": "73a888cd46e1acd4184645f0a1ef63ddb1c428b8",
          "md5": "62df248b4d703cc73936081178bb4495"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-9.0.1.aar",
          "url": "viewbinding-9.0.1.aar",
          "size": 1861,
          "sha512": "cca33022607d03648a8e4df5253791f3071e6db503efe57747e88a3f8ab089c63f5c9c3d632e86a426d7d9164960c26d96e7a7325aa74d436fc84cb973c71867",
          "sha256": "9c6875bea4e43027209a3a7ef3d99524aca7c16797a2e6794afc62fbfbab7e28",
          "sha1": "73a888cd46e1acd4184645f0a1ef63ddb1c428b8",
          "md5": "62df248b4d703cc73936081178bb4495"
        }
      ]
    }
  ]
}
