{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-fragment-ktx",
    "version": "2.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13444738"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.9.0-sources.jar",
          "url": "navigation-fragment-ktx-2.9.0-sources.jar",
          "size": 4462,
          "sha512": "dc713dfa1a2cecc2b4c18b4c984358f63203ecba9d082f864c2618b0dba43b2c4316b04389389a69ebe6a2680830fa1f15af1a43af22a0ebd00271b6cd179321",
          "sha256": "4875a0ebc58b264092e4ed155500a9d04a17c0f52fd6466d7710f3c9fc20e27c",
          "sha1": "d6e7d531ce96506b7de720eb12aecd6e13ae750b",
          "md5": "2191c706daa2f1fe4fce153a390817b3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.9.0.aar",
          "url": "navigation-fragment-ktx-2.9.0.aar",
          "size": 5814,
          "sha512": "d1bd5e848257bd76b0b1492143f45b03c2ffe8974aa37cf849255929c7e721b2f5815f3e5faf3e618e5332f23a036105c8c343f89f1f933fe8fd0fc057eac97c",
          "sha256": "8484a608a76e0330112a7090251f8dd4f90a721f4598aa52f2924f091c67d93b",
          "sha1": "4332ff77d2978527904577802f2e229a8d44b937",
          "md5": "fa992c76e25f6572efb098829345da86"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.9.0.aar",
          "url": "navigation-fragment-ktx-2.9.0.aar",
          "size": 5814,
          "sha512": "d1bd5e848257bd76b0b1492143f45b03c2ffe8974aa37cf849255929c7e721b2f5815f3e5faf3e618e5332f23a036105c8c343f89f1f933fe8fd0fc057eac97c",
          "sha256": "8484a608a76e0330112a7090251f8dd4f90a721f4598aa52f2924f091c67d93b",
          "sha1": "4332ff77d2978527904577802f2e229a8d44b937",
          "md5": "fa992c76e25f6572efb098829345da86"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.9.0"
          },
          "reason": "navigation-fragment-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.9.0-versionMetadata.json",
          "url": "navigation-fragment-ktx-2.9.0-versionMetadata.json",
          "size": 3940,
          "sha512": "3c43f699db7e49ba4a9cf5543977e303280f9c4d4c6801dce8bd4498f85ae098a8e91992a4ea1804ddc6b19f4da4d67bb65e51b9b0d2894cd3e10a6085a32cf2",
          "sha256": "fd61c55e26a2a30413768944fb579261665d701233b4aa310e5ecc96611ecb27",
          "sha1": "68cd1fa3e4e3883aed07ba82cdf89640c8e9f5ce",
          "md5": "fa70140253edeff321c532937362ab69"
        }
      ]
    }
  ]
}