{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.credentials",
    "module": "credentials",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.3.0-sources.jar",
          "url": "credentials-1.3.0-sources.jar",
          "size": 196171,
          "sha512": "689ed248be062a82de62aaa908f5826535bba42a8224952a27b41a302061170209b6654f3c8bac45af26b153abe72fa2161bba6c13df800b53f801b243508b09",
          "sha256": "d09b1e7f43398891ad922e7410577eaabe263c73e014838ef520a13157773614",
          "sha1": "4d7ce02f2fa99c7e8a042b362f4d74d1b0847a54",
          "md5": "8127fc1d422d50480e721e2c4f744ba5"
        },
        {
          "name": "credentials-1.3.0-samples-sources.jar",
          "url": "credentials-1.3.0-samples-sources.jar",
          "size": 7243,
          "sha512": "4802d83b3197e0faf36b8968e23723ad598d1954bdc5353bbe7193cd28f00fb0d41e98b28df9cae41584153608b7e52215c29dc8089d8785b2a4b83f34e4a003",
          "sha256": "fe1e7e44cf21e3cfd6858d14fba9da11aff6a3dc9d25b2bb634afb5a7dae73ae",
          "sha1": "1c39e28debbbbfaf621ec1643048b3ae9e7c745e",
          "md5": "44b66a46acc1d1332daf97f2211fe1a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.3.0.aar",
          "url": "credentials-1.3.0.aar",
          "size": 455575,
          "sha512": "f3df30e268f720ef67aee188a83dd58dda3477352eb08ef0d60620f3734cd034ba0a4e4cd56eaff32b472a6a47b8c4b07c7fc93581414327f333c51adb97f3fb",
          "sha256": "b33c1a3e2d41fc3a163dd161d3334d2510d9b2086ed923c60a6f79ee22b78984",
          "sha1": "497515237ee3a87f9688fc592c4fb0a16d24bd53",
          "md5": "458bee1a1929a2c7d609f19ccb74daac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.3.0.aar",
          "url": "credentials-1.3.0.aar",
          "size": 455575,
          "sha512": "f3df30e268f720ef67aee188a83dd58dda3477352eb08ef0d60620f3734cd034ba0a4e4cd56eaff32b472a6a47b8c4b07c7fc93581414327f333c51adb97f3fb",
          "sha256": "b33c1a3e2d41fc3a163dd161d3334d2510d9b2086ed923c60a6f79ee22b78984",
          "sha1": "497515237ee3a87f9688fc592c4fb0a16d24bd53",
          "md5": "458bee1a1929a2c7d609f19ccb74daac"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.3.0-versionMetadata.json",
          "url": "credentials-1.3.0-versionMetadata.json",
          "size": 55073,
          "sha512": "5fe73f619ac7e4859924601aba5fcc5c7b4a9fda1f7dc9198a54a1838dd584b0b203b72930093d81db95e0eaeead182c43896e967995859ede8317a59a1a41fe",
          "sha256": "f687d08ec06f9af4db61389ae81a4fb0b0df3e78f883fff8870578cee12ad8d7",
          "sha1": "2110fce377b46cc19481e74216e1cf2a3bc5f5c2",
          "md5": "b1eb83acf0afa781e1c775f3bab77e59"
        }
      ]
    }
  ]
}